### ISSUE TITLE
Kubernetes Strategy OTP 26 Incompatibility

### ISSUE THREAD

**Issue by maennchen** [bitwalker/libcluster#193]
### Steps to reproduce

- Configuration Used

```elixir
def start(_type, _args) do
  strategy =
    with {:ok, app_name} <- System.fetch_env("RELEASE_NAME"),
          {:ok, selector} <- System.fetch_env("KUBERNETES_POD_SELECTOR"),
          {:ok, namespace} <- System.fetch_env("KUBERNETES_NAMESPACE") do
      [
        k8s: [
          strategy: Cluster.Strategy.Kubernetes,
          config: [
            mode: :dns,
            kubernetes_node_basename: app_name,
            kubernetes_selector: selector,
            kubernetes_namespace: namespace,
            polling_interval: 10_000
          ]
        ]
      ]
    else
     # ... irrelevant for this issue
    end

  Supervisor.start_link(
    [
      {Cluster.Supervisor,
        [
          strategy,
          [name: Sustema.CompanyCluster.Cluster.Supervisor]
        ]}
    ],
    strategy: :one_for_one,
    name: Sustema.CompanyCluster.Supervisor
  )
end
```

- Strategy Used: `Cluster.Strategy.Kubernetes`
- Errors/Incorrect Behaviour Encountered

```
    ** (EXIT) shutdown: failed to start child: :k8s
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, :enoent}
                (public_key 1.14) pubkey_os_cacerts.erl:38: :pubkey_os_cacerts.get/0
                (inets 9.0) httpc.erl:476: :httpc.ssl_verify_host_options/1
                (inets 9.0) httpc.erl:1012: :httpc.http_options_default/0
                (inets 9.0) httpc.erl:927: :httpc.http_options/1
                (inets 9.0) httpc.erl:771: :httpc.handle_request/9
                (libcluster 3.3.2) lib/strategy/kubernetes.ex:241: Cluster.Strategy.Kubernetes.get_nodes/1
                (libcluster 3.3.2) lib/strategy/kubernetes.ex:125: Cluster.Strategy.Kubernetes.load/1
                (libcluster 3.3.2) lib/strategy/kubernetes.ex:108: Cluster.Strategy.Kubernetes.init/1
```

### Description of issue

- What are the expected results?

  * No error
  * preferrably `/run/secrets/kubernetes.io/serviceaccount/ca.crt` is used for the TLS connection

- Is the documentation incorrect?

  * No

- Additional Context
  * Works on OTP `25.3.2`
  * Fails on OTP `26.0`

**Comment by maennchen** [comment]
Looking at this a bit further, the error itself is actually a problem in OTP: https://github.com/erlang/otp/issues/7295

I'll therefore close the issue. PR #194 is still an improvement though and resolved the problem on the OTP side as well since the CACerts don't have to be loaded at all.
