### ISSUE TITLE
New release needed for OTP 21.0 compatibility

### ISSUE THREAD

**Issue by seantanly** [bitwalker/libcluster#74]
With the release of OTP 21.0, the latest available version 2.5.0 on Hex isn't compatible with that. 

```
01:36:19.228 [info]  Application libcluster exited: Cluster.App.start(:normal, []) returned an error: shutdown: failed to start child: Cluster.Strategy.Epmd
    ** (EXIT) an exception was raised:
        ** (RuntimeError) net_kernel.connect/1 is undefined!
            (libcluster) lib/strategy/strategy.ex:117: Cluster.Strategy.ensure_exported!/3
            (libcluster) lib/strategy/strategy.ex:43: anonymous fn/6 in Cluster.Strategy.connect_nodes/4
            (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
            (libcluster) lib/strategy/strategy.ex:41: Cluster.Strategy.connect_nodes/4
            (libcluster) lib/strategy/epmd.ex:27: Cluster.Strategy.Epmd.start_link/1
            (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
            (stdlib) supervisor.erl:1157: :supervisor.children_map/4
            (stdlib) supervisor.erl:315: :supervisor.init_children/2
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Any chance we can get a new libcluster version deployed?

**Comment by seantanly** [comment]
I tested `Cluster.Strategy.Epmd` and `Cluster.Strategy.ErlangHosts` and the local nodes are able to connect successfully.

I have not used `Cluster.Strategy.Gossip` before, and tried making it work locally on a MacBook but couldn't. Turning on debugging yields a lot of `23:46:25.230 [debug] [libcluster:yojee_gossip] heartbeat` messages without the nodes connecting. Is there a setup/troubleshooting guide for Gossip?

Thank you for this great library!

**Comment by xadhoom** [comment]
> I have not used Cluster.Strategy.Gossip before, and tried making it work locally on a MacBook but couldn't. Turning on debugging yields a lot of 23:46:25.230 [debug] [libcluster:network_gossip] heartbeat messages without the nodes connecting. Is there a setup/troubleshooting guide for Gossip?

Gossip uses multicast packets over the network. 
I'm not a OSX expert, but probably you need to enable multicast on the network adapter or check if the firewall is not blocking them or there's some other setting that is preventing mcast packets from being sent/received.
