### ISSUE TITLE
No function clause matching in Mix.Releases.Runtime.Control.ping/2   

### ISSUE THREAD

**Issue by idyll** [bitwalker/libcluster#79]
I apologize if this is just a dumb config issue, but I've been using libcluster since Kubernetes support was added without issue until today.

I am trying to deploy and keep getting the following error instead of a ping. Any thoughts?

```
** (FunctionClauseError) no function clause matching in Mix.Releases.Runtime.Control.ping/2    
    
    The following arguments were given to Mix.Releases.Runtime.Control.ping/2:
    
        # 1
        []
    
        # 2
        %{cookie: :totallyFakeCookie}
    
    Attempted function clauses (showing 1 out of 1):
    
        def ping(+_args+, -%{peer: peer}-)
    
    (distillery) lib/mix/lib/releases/runtime/control.ex:395: Mix.Releases.Runtime.Control.ping/2
    (distillery) lib/entry.ex:44: Mix.Releases.Runtime.Control.main/1
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/code.ex:232: Code.eval_string/3
```

**Comment by idyll** [comment]
Yup. Just hat to type it out and hit submit. Trying newer distillery...
