### ISSUE TITLE
possible race condition when ensuring exported functions.

### ISSUE THREAD

**Issue by syfgkjasdkn** [bitwalker/libcluster#88]
👋

While [playing around with libcluster and partisan](https://github.com/syfgkjasdkn/partisan-libcluster-example) I keep getting the following error when I kill one of the nodes and then start it again:

```erl
21:15:36.313 [error] CRASH REPORT Process <0.311.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
21:15:36.314 [error] Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
21:15:36.314 [error] Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
21:15:36.314 [error] Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.305.0> exit with reason shutdown in context child_terminated
21:15:36.316 [error] gen_server <0.313.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
```

Seems like `:libcluster` tries to check that [`PC.list_nodes/0` is exported](https://github.com/syfgkjasdkn/partisan-libcluster-example/blob/932cfd5fb2586651aa6670b5aeea00312987b618/config/dev.exs#L8-L10) before the `PC` is loaded?

**Comment by syfgkjasdkn** [comment]
```
21:31:19.220 [error] Process #PID<0.342.0> terminating
** (RuntimeError) Elixir.PC.list_nodes/0 is undefined!
    (libcluster) lib/strategy/strategy.ex:156: Cluster.Strategy.ensure_exported!/3
    (libcluster) lib/strategy/strategy.ex:40: Cluster.Strategy.connect_nodes/4
    (libcluster) lib/strategy/gossip.ex:198: Cluster.Strategy.Gossip.handle_heartbeat/2
    (libcluster) lib/strategy/gossip.ex:140: Cluster.Strategy.Gossip.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Initial Call: Cluster.Strategy.Gossip.init/1
Ancestors: [PC.Cluster.Supervisor, PC.Supervisor, #PID<0.311.0>]
Message Queue Length: 1
Messages: [{:udp, #Port<0.30>, {192, 168, 1, 38}, 45892, <<104, 101, 97, 114, 116, 98, 101, 97, 116, 58, 58, 131, 116, 0, 0, 0, 1, 100, 0, 4, 110, 111, 100, 101, 100, 0, 10, 97, 108, 105, 99, 101, 64, 109, 97, 99, 50>>}]
Links: [#PID<0.337.0>, #Port<0.30>]
Dictionary: [rand_seed: {%{bits: 58, jump: #Function<8.10897371/1 in :rand.mk_alg/1>, next: #Function<5.10897371/1 in :rand.mk_alg/1>, type: :exrop, uniform: #Function<6.10897371/1 in :rand.mk_alg/1>, uniform_n: #Function<7.10897371/2 in :rand.mk_alg/1>, weak_low_bits: 1}, [150125270521226321 | 274968339812631103]}]
Trapping Exits: false
Status: :running
Heap Size: 987
Stack Size: 27
Reductions: 188852

21:31:19.221 [error] Child Cluster.Strategy.Gossip of Supervisor PC.Cluster.Supervisor terminated
** (exit) an exception was raised:
    ** (RuntimeError) Elixir.PC.list_nodes/0 is undefined!
        (libcluster) lib/strategy/strategy.ex:156: Cluster.Strategy.ensure_exported!/3
        (libcluster) lib/strategy/strategy.ex:40: Cluster.Strategy.connect_nodes/4
        (libcluster) lib/strategy/gossip.ex:198: Cluster.Strategy.Gossip.handle_heartbeat/2
        (libcluster) lib/strategy/gossip.ex:140: Cluster.Strategy.Gossip.handle_info/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Pid: #PID<0.342.0>
Start Call: Cluster.Strategy.Gossip.start_link([%Cluster.Strategy.State{config: [], connect: {PC, :connect_node, []}, disconnect: {PC, :disconnect_node, []}, list_nodes: {PC, :list_nodes, []}, meta: nil, topology: :example}])
Restart: :permanent
Shutdown: 5000
```
